# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-16 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20190816_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('title', 'weight')]),
        ),
    ]
