# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-15 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20190814_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
