# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-19 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_student_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brithday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('date', models.DateField()),
            ],
        ),
    ]
