# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-02 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_author_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='book',
            name='good',
        ),
    ]
