# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-18 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
                ('current_date', models.DateField()),
            ],
        ),
    ]
