# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-25 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190724_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Publish'),
        ),
    ]
