# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-07-25 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190725_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='sex',
            field=models.CharField(default='male', max_length=6),
        ),
    ]
